// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezqgjcauznmqhdzrjolr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cWdqY2F1em5tcWhkenJqb2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NjkyMTYsImV4cCI6MjA4MzU0NTIxNn0.dZOcEo6oipyYr-gpO82saGFSmRPa4rkJ7ahqfobxZUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});